/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package duanqlbanquanao.view;

import duanqlbanquanao.model.HoaDon;
import duanqlbanquanao.model.NhanVien;
import duanqlbanquanao.service.HoaDonService;
import duanqlbanquanao.service.NhanVienService;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class FrHoaDon extends javax.swing.JInternalFrame {

    /**
     * Creates new form QLNV
     */
    DefaultTableModel model;
    HoaDonService hoaDonService;
    private SimpleDateFormat sdf;

    public FrHoaDon() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);

        model = (DefaultTableModel) tblTable.getModel();
        hoaDonService = new HoaDonService();
        sdf = new SimpleDateFormat("MM/dd/yyyy");
        layDuLieu();
    }

    private void layDuLieu() {
        List<HoaDon> list = this.hoaDonService.layDanhSach();
        for (HoaDon hd : list) {
            int ma = hd.getMa();
            String nguoiTao = hd.getNguoiTao();
            Date ngayTao = hd.getNgayTao();
            String trangThai = "";
            if (hd.getTrangThai() == 1) {
                trangThai = "Đã Thanh Toán";
            } else {
                trangThai = "Chưa Thanh Toán";
            }
            model.addRow(new Object[]{ma, nguoiTao, ngayTao, trangThai
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtSearch = new javax.swing.JTextField();
        txtNguoiTao = new javax.swing.JTextField();
        txtNgayTao = new javax.swing.JTextField();
        rdDaTT = new javax.swing.JRadioButton();
        rdCTT = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTable = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();

        buttonGroup1.add(rdDaTT);
        rdDaTT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdDaTT.setSelected(true);
        rdDaTT.setText("Đã Thanh Toán");

        buttonGroup1.add(rdCTT);
        rdCTT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdCTT.setText("Chưa Thanh Toán");

        tblTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Hoá Đơn", "Người Tạo", "Ngày Tạo", "Trạng Thái"
            }
        ));
        tblTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTable);

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanqlbanquanao/image/Add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanqlbanquanao/image/Edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanqlbanquanao/image/Delete.png"))); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanqlbanquanao/image/Refresh.png"))); // NOI18N
        btnClear.setText("Clear");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("QUẢN LÝ HOÁ ĐƠN");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Người Tạo");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Ngày Tạo");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Trạng Thái");

        jLabel6.setText("Mã Hoá Đơn");

        txtMaHD.setText("___");

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duanqlbanquanao/image/Search.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNguoiTao)
                                            .addComponent(txtSearch)
                                            .addComponent(txtNgayTao, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(37, 37, 37)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addComponent(btnSearch)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rdDaTT, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rdCTT, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtMaHD))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel2)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMaHD))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNguoiTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(jLabel3))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa)
                    .addComponent(btnClear)
                    .addComponent(jLabel4))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdCTT)
                    .addComponent(rdDaTT)
                    .addComponent(jLabel5))
                .addGap(63, 63, 63)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
//        HoaDon hd = validateHoaDon();
//        if (hd != null) {
//            themThongTin(hd);
//            model.setRowCount(0);
//            layDuLieu();
//            JOptionPane.showMessageDialog(this, "Thêm Thành Công");
//        } else {
//            JOptionPane.showMessageDialog(this, "Thêm Thất Bại");
//        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int index = tblTable.getSelectedRow();
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "Moi ban chon");
            return;
        }
        int choice = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Xoá Không?", "delete", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            int ma = (int) model.getValueAt(index, 0);
            xoaThongTin(ma);
            model.removeRow(index);
            JOptionPane.showMessageDialog(this, "Xoa thanh cong");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTableMouseClicked
        int index = tblTable.getSelectedRow();
        String nguoiTao = model.getValueAt(index, 1).toString();
        String ngayTao = model.getValueAt(index, 2).toString();
        String trangThai = model.getValueAt(index, 3).toString();
        String ma = model.getValueAt(index, 0).toString();
        txtNguoiTao.setText(nguoiTao);
        txtNgayTao.setText(ngayTao);
        txtMaHD.setText(ma);
        if (trangThai.equalsIgnoreCase("Đã Thanh Toán")) {
            rdDaTT.setSelected(true);
        }
        if (trangThai.equalsIgnoreCase("Chưa Thanh Toán")) {
            rdCTT.setSelected(true);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_tblTableMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
//         HoaDon hd = new HoaDon();
//        int index = tblTable.getSelectedRow();
//        int ma = Integer.parseInt(txtMaHD.getText());
//        hd.setMa(ma);
//        String nguoiTao = txtNguoiTao.getText();
//        Date ngayTao = txtNgayTao.getText();
//        int trangThai = Integer.parseInt(rdDaTT.getText());
//        hd.setNguoiTao(nguoiTao);
//        hd.setNgayTao(ngayTao);
//        hd.setTrangThai(trangThai);
//        this.hoaDonService.capNhatThongTin(hd);
//        loadTableHD();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String txt = txtSearch.getText();
        modelHD = (DefaultTableModel) tblTable.getModel();
        modelHD.setRowCount(0);
        List<HoaDon> dsHoaDons = hoaDonService.search(txt);
        for (HoaDon hd : dsHoaDons) {
            modelHD.addRow(new Object[]{
                hd.getMa(), hd.getNguoiTao(), hd.getNgayTao(), hd.getTrangThai()
            });
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed
    private void xoaThongTin(int ma) {
        this.hoaDonService.xoaThongTin(ma);
    }

    private void themThongTin(HoaDon hd) {
        this.hoaDonService.themThongTin(hd);

    }
    DefaultTableModel modelHD;

    private void loadTableHD() {
        modelHD = (DefaultTableModel) tblTable.getModel();
        modelHD.setRowCount(0);
        List<HoaDon> dsHoaDons = hoaDonService.layDanhSach();
        for (HoaDon hd : dsHoaDons) {
            modelHD.addRow(new Object[]{
                hd.getNguoiTao(), hd.getNgayTao(), hd.getTrangThai()
            });
        }
    }

//    private HoaDon validateHoaDon() {
//        String nguoiTao = txtNguoiTao.getText();
//        if (nguoiTao.isBlank()) {
//            JOptionPane.showMessageDialog(this, "Nhap ten nguoi tao");
//            return null;
//        }
//
//        String ngayTao = txtNgayTao.getText();
//        if (ngayTao.isBlank()) {
//            JOptionPane.showMessageDialog(this, "Nhap ngay tao");
//            return null;
//        }
//        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
//        dateFormat.setLenient(false);
//
//        try {
//            dateFormat.parse(ngayTao);
//        } catch (ParseException e) {
//            JOptionPane.showMessageDialog(this, "Ngay tao khong hop le");
//            return null;
//        }
//
//        int trangThai = 0;
//        if (rdDaTT.isSelected()) {
//            trangThai = 1;
//        }
//        if (rdCTT.isSelected()) {
//            trangThai = 0;
//        }
//
//        HoaDon hd = new HoaDon();
//        hd.setNguoiTao(nguoiTao);
//        hd.setNgayTao(ngayTao);
//        hd.setTrangThai(trangThai);
//        return hd;
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdCTT;
    private javax.swing.JRadioButton rdDaTT;
    private javax.swing.JTable tblTable;
    private javax.swing.JLabel txtMaHD;
    private javax.swing.JTextField txtNgayTao;
    private javax.swing.JTextField txtNguoiTao;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
